### ISSUE TITLE
[Launcher] Open seed doesn't open the game

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/ui#22]
When launching through a seedfile, instead of focusing the game window, the electron ui window gets focused

**Comment by timoschwarzer** [comment]
Done, thanks :)

**Comment by SiriusAshling** [comment]
Hm I tried to install from https://github.com/ori-rando/build/actions/runs/1271401950 and still have the issue

**Comment by timoschwarzer** [comment]
Can't reproduce :sweat_smile:
